# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Meeting Point
email: themeetingpoint@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Meeting Point is a collective of independent body workers and
  mental health practitioners who believe support and acceptance of
  complicated bodies is a social justice issue.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://themeetingpoint.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
phone: "(877) 207-8479"
address: "3464 Washington Street, JP"
addressLink: "https://goo.gl/maps/pHSDaDkRcBt"
# twitter_username: jekyllrb
# github_username:  jekyll
facebook_username: themeetingpointJP

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - psychotherapy.md
  - bodywork.md
  - groups.md
  - events.md

collections:
  bodywork:
    output: true
  psychotherapy:
    output: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
